### ISSUE TITLE
In mobile Safari, env vars tab is either not opening, or taking a lot of time to open

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise-workflow-editor#298] opened 2018-07-06 13:53 UTC
User who reported: https://discuss.bitrise.io/t/website-is-unusable-on-safari/5597/2

**Comment by fwigorcferreira** [comment] 2018-07-06 14:02
This bug was seem on:

```
iPhone X
iOS 11.4
Date: 06/07/2018
```

And the status is that it does not open! Even if I leave the Safari open for more than 5 minutes.

**Comment by doomsayer13** [comment] 2018-08-01 10:49
Hi @fwigorcferreira,
We were not able to reproduce the issue, but we changed the tab selector logic and added some progress indicators, so it should be more informative to understand what happening there.
The fix is released in offline mode (v1.1.24), but soon will be released to the online mode too.
Thanks for reporting and sorry for the inconveniences.

**Comment by fwigorcferreira** [comment] 2018-08-01 10:51
@doomsayer13 I'll test it once it is available on Bitrise web. But, right now, I can reproduce it 100% of time, on any iPhone, any Safari version. When accessing the env var tab, the browser freezes.

**Comment by fwigorcferreira** [comment] 2018-08-01 11:04
@doomsayer13 The bug is easily reproducible! In 100% of the iPhone devices that I have access to (iPhone X, iPhone 6, iPhone 6s), and multiple iOS versions (iOS 11.3, iOS 11.0.1, iOS 10.3). Here is a video showing how it is impossible to access it on Safari (you can see in the address bar that I'm trying to interact with the page): https://www.dropbox.com/s/u85ykdk64i9e8zd/IMG_1203.TRIM.MOV?dl=1

**Comment by doomsayer13** [comment] 2018-08-02 11:36
Hi,
Sorry for the inconveniences. We will check it again.
Can you please enable Bitrise Support User on one of the app where you are facing the issue and we will check it?
Also did you tried to clear History and Website Data and reload the page after that?

PS: just want to show you that the fix is working on our test device on which we had a loading issue previously - https://we.tl/uuncTeWxsk

**Comment by fwigorcferreira** [comment] 2018-08-02 12:11
@doomsayer13 I tried to clean history, and website data. Tried on private mode, different devices. And freshly refreshed device. And faced the page freezing, and unable to access the env var on all the cases.

**Comment by fwigorcferreira** [comment] 2018-08-02 12:12
@doomsayer13 I have enabled Bitrise Support Users on 3 projects, linked those in the discuss.bitrise.io thread, and sent in the Bitrise support chat.

**Comment by doomsayer13** [comment] 2018-08-02 12:27
Thank you. We'll check it and update you ASAP.

**Closed** 2024-08-29 13:50 UTC
Labels: bug
