### ISSUE TITLE
Clicking the App Name doesn't do anything

### ISSUE THREAD

**Issue by bennybates** [bitrise-io/bitrise-workflow-editor#110] opened 2017-05-12 16:52 UTC
I would expect it to bring me back to the "Builds" page I think. Currently nothing happens.

![image](https://cloud.githubusercontent.com/assets/1596695/26008210/cc8cb2c2-3711-11e7-88bc-4d784be69e3b.png)

**Comment by viktorbenei** [comment] 2017-05-12 17:11
Thanks for reporting @bennybates !

Duplicate of: https://github.com/bitrise-io/bitrise-workflow-editor/issues/105

**Closed by viktorbenei** 2017-05-12 17:11 UTC
Labels: duplicate
