### ISSUE TITLE
Unable to modify workflows

### ISSUE THREAD

**Issue by nhammond101** [bitrise-io/bitrise-workflow-editor#523] opened 2020-09-15 21:45 UTC
Making any changes to the workflows or the bitrise.yml doesn't work.

The editor will hang indefinitely, and in the devtools console, and error referring to a property on an undefined object is shown.
![Screenshot 2020-09-15 at 22 41 22](https://user-images.githubusercontent.com/456479/93268114-971a4580-f7a4-11ea-9246-a77f4497a795.png)

Reproduction steps:
1. Create new Project
1. Open workflow-editor
1. Modify any step and save

Bitrise CLI version: 1.42.0
Bitrise workflow-editor version: 1.3.41
Browser: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
OS: macOS Catalina 10.15.6

**Comment by dan-overton** [comment] 2020-09-16 08:19
I'm experiencing the same issue on the same platform, against the default bitrise.yml created with 'bitrise.init' (ionic + android). 

The issue is occurring on this line: https://github.com/bitrise-io/bitrise-workflow-editor/blob/ac8c8cfd3162cbbe792b67d7bf9939b22660802d/source/javascripts/controllers/_MainController.js.erb#L389

because the `pipelineConfig` property of the appService is undefined.

**Comment by dan-overton** [comment] 2020-09-16 09:12
Digging a bit deeper this is due to this line: https://github.com/bitrise-io/bitrise-workflow-editor/blob/efb4ca33707d2277f10609800ca922d861cc8e3a/source/javascripts/services/_requestService.js.erb#L518 

The editor skips getting the pipeline config in CLI mode only, with the message 'Getting pipeline config is only available in website mode'. The view model save then assumes it's there and crashes. I guess the save needs to check for either the mode (website/cli) or that the pipeline config exists.

**Comment by Ozonid** [comment] 2020-10-08 14:04
Hello!
Sorry for the late reply, the issue should be fixed in the latest release. Sorry for the inconvenience.

**Closed** 2020-10-09 09:39 UTC
