### ISSUE TITLE
Make it simple to add custom steps, by just providing the git clone URL in the editor.

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise-workflow-editor#165] opened 2017-06-14 11:03 UTC
Make it simple to add custom steps, by just providing the git clone URL in the editor. Something like: click on the + (add step) button, and in the right sidebar there should be an option to "add a custom step via git clone URL" or similar.

**Comment by viktorbenei** [comment] 2017-06-14 11:05
Related discussion: https://github.com/bitrise-io/bitrise-steplib/pull/1045

**Comment by doomsayer13** [comment] 2018-09-18 14:39
I'm going to close this ticket because this is a duplicate of [https://github.com/bitrise-io/bitrise-workflow-editor/issues/140](url) issue report.
Feature request card is already created in our internal task tracking system ;)

**Closed by doomsayer13** 2018-09-18 14:39 UTC
Labels: enhancement
