### ISSUE TITLE
Loading progress indicator stuck

### ISSUE THREAD

**Issue by doomsayer13** [bitrise-io/bitrise-workflow-editor#78] opened 2017-04-03 12:26 UTC
![screen shot 2017-04-03 at 14 15 17](https://cloud.githubusercontent.com/assets/8809762/24608806/69511cbe-1878-11e7-896f-fa2f8953564c.png)

Select a tab, make some changes, click on another tab, then do not click on "Save" or "Cancel" buttons in a popup just click somewhere else. The popup will disappear, but the "Loading..." progress indicator will be still displayed and you will not be able to Save the changes or to discard them.

**Comment by erosdome** [comment] 2017-04-03 12:59
closing, duplicate of #76

**Closed by erosdome** 2017-04-03 12:59 UTC
