### ISSUE TITLE
Show step input/output description

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise-workflow-editor#49] opened 2017-02-09 13:45 UTC
Inputs' and outputs' description should be visible somewhere on the UI

**Comment by viktorbenei** [comment] 2017-02-13 17:47
Duplicate of: https://github.com/bitrise-io/bitrise-workflow-editor/issues/51 (includes more info ;) )

**Closed by viktorbenei** 2017-02-13 17:47 UTC
Labels: duplicate
