### ISSUE TITLE
Error loading steplib specs / Missing output data

### ISSUE THREAD

**Issue by fadookie** [bitrise-io/bitrise-workflow-editor#39] opened 2017-02-03 16:26 UTC
When I try to run workflow-editor `0.9.1` on my bitrise step repos (ex. [aws-device-farm-test-packager](https://github.com/peartherapeutics/bitrise-aws-device-farm-test-packager)) I get the following error:
<img width="393" alt="screen shot 2017-02-03 at 8 23 45 am" src="https://cloud.githubusercontent.com/assets/110764/22598982/1f095ba6-e9ea-11e6-888c-42635aef6cf4.png">

Js console shows:
```
Error: Error loading steplib specs.
    at main.js:53458
    at processQueue (main.js:27448)
    at main.js:27464
    at Scope.$eval (main.js:28716)
    at Scope.$digest (main.js:28532)
    at Scope.$apply (main.js:28824)
    at done (main.js:23162)
    at completeRequest (main.js:23360)
    at XMLHttpRequest.requestLoaded (main.js:23301)
```

Terminal shows:
```
$ bitrise :workflow-editor
Starting API server at http://localhost:3645
Open workflow editor in browser ...
 => GET: /api/bitrise-yml.json - 14.842118ms ()
Missing output data
 => GET: /api/spec - 40.626267ms ()
```

**Comment by fadookie** [comment] 2017-02-03 16:27
Looks like this might be a dupe of https://github.com/bitrise-io/bitrise-workflow-editor/issues/38

**Comment by erosdome** [comment] 2017-02-03 16:53
Hi, thanks for reporting the issue, it is related to the release process. A new version vill arrive shortly:

https://discuss.bitrise.io/t/offline-workflow-editor-workflow-editor-v2-v0-9-1-released/626/2?u=erosdome

**Comment by godrei** [comment] 2017-02-03 17:03
Hi @fadookie ,
sorry for the faulty release. 
We shared a new version with fixed plugin definition: [0.9.2](https://github.com/bitrise-io/bitrise-workflow-editor/releases/tag/0.9.2)

**Comment by viktorbenei** [comment] 2017-02-03 17:07
Let us know if you'd still have any this issue with v0.9.2 @fadookie , and thanks for reporting the issue! ;)

**Comment by fadookie** [comment] 2017-02-03 17:30
@viktorbenei I can reproduce on the step-template with 0.9.2.
```
step-template(master)$ bitrise plugin update workflow-editor
INFO[09:26:17] Installing new version (0.9.2) of plugin (workflow-editor)

INFO[09:26:18] Installed plugin found with version (0.9.1), overriding it...


INFO[09:26:25] Plugin (workflow-editor) with version (0.9.2) installed

Bitrise Workflow Editor.

step-template(master)$ bitrise :workflow-editor
Starting API server at http://localhost:3645
Open workflow editor in browser ...
 => GET: /api/bitrise-yml.json - 14.496686ms ()
empty output data
 => POST: /api/spec - 25.262129ms (application/json;charset=UTF-8)
```
<img width="1438" alt="screen shot 2017-02-03 at 9 28 09 am" src="https://cloud.githubusercontent.com/assets/110764/22601309/371ccd28-e9f3-11e6-9f19-5277fbb1404c.png">

**Comment by viktorbenei** [comment] 2017-02-03 17:32
So, you ran this in the directory of https://github.com/peartherapeutics/bitrise-aws-device-farm-test-packager , with this bitrise.yml https://github.com/peartherapeutics/bitrise-aws-device-farm-test-packager/blob/master/bitrise.yml right?

**Comment by viktorbenei** [comment] 2017-02-03 17:36
Issue Reproduced.

I think it's because you have a local file reference in your `bitrise.yml`, that should be supported soon, in an upcoming version of the workflow editor, 0.9.2 does not support it yet.

**Comment by fadookie** [comment] 2017-02-03 17:38
@viktorbenei yep. I was saying I can reproduce this with https://github.com/bitrise-steplib/step-template as well. Thanks for the update.

**Comment by bootstraponline** [comment] 2017-03-05 17:02
I'm seeing the same error. https://github.com/bitrise-io/bitrise-workflow-editor/issues/65

my bitrise.yml is simple.

- https://gist.github.com/bootstraponline/01c50f24ecd7f971bf6394e1699abc99

**Comment by viktorbenei** [comment] 2017-03-05 18:13
@bootstraponline - checked the gist, saved as `bitrise.yml` then started the workflow editor - it loaded for me without any issue.

What's your

```
bitrise version
bitrise :workflow-editor version
```
?

**Comment by bootstraponline** [comment] 2017-03-05 18:17
```
~/code/other/react_native_automation_bitrise  bitrise version
1.5.4
 ~/code/other/react_native_automation_bitrise  bitrise :workflow-editor version
0.9.6
```

**Comment by bootstraponline** [comment] 2017-03-05 18:18
is `bitrise.yml` not suppose to be at the folder root directory or something? I saved it to `react_native_automation_bitrise` and that's where I ran the command.

**Comment by viktorbenei** [comment] 2017-03-05 18:20
> is bitrise.yml not suppose to be at the folder root directory or something?

All what matters is that you have to be in that dir when you run `bitrise :workflow-editor` - that reads the `bitrise.yml` from that dir.

My guess is that you ran `bitrise :workflow-editor` in another dir, with a different bitrise.yml ; the yml you linked should work and it did when I tested.

**Comment by bootstraponline** [comment] 2017-03-05 18:22
I tried again and it's still broken. Here are the exact commands:

```
$ wget https://gist.githubusercontent.com/bootstraponline/01c50f24ecd7f971bf6394e1699abc99/raw/34a770775b9ffbc78034fa68393de4fed39e568d/bitrise.yml
$ bitrise :workflow-editor
```

the above works for you?

**Comment by viktorbenei** [comment] 2017-03-05 18:22
Just tested it again, worked as expected:

```
mkdir /tmp/bitrise-quick-test
cd /tmp/bitrise-quick-test/
wget -O bitrise.yml https://gist.githubusercontent.com/bootstraponline/01c50f24ecd7f971bf6394e1699abc99/raw/34a770775b9ffbc78034fa68393de4fed39e568d/bitrise.yml
bitrise :workflow-editor
```

**Comment by bootstraponline** [comment] 2017-03-05 18:24
I ran your sequence precisely and the error is the same. There must be some difference between our environments.

**Comment by bootstraponline** [comment] 2017-03-05 18:24
```
$ go version
go version go1.8 darwin/amd64
```

maybe the go version?

**Comment by viktorbenei** [comment] 2017-03-05 18:24
I'd say we should open a new issue for this, as this is not related to this thread - you don't have any `git::` or `path::` step refs in your workflow, which was the original reported issue here.

**Comment by bootstraponline** [comment] 2017-03-05 18:24
Ok, I'll restore issue #65 & will track it there.

**Comment by erosdome** [comment] 2017-05-19 11:35
closing due to local and git URL specified steps being featured since.

**Closed by erosdome** 2017-05-19 11:35 UTC
Labels: bug
