### ISSUE TITLE
Navigation from workflow editor to app page does not work

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#128] opened 2017-05-17 10:36 UTC
Clicking on the app name in the header causes only URL change in browser's address bar (from `https://www.bitrise.io/app/1d190f1c0e4c8486#/workflow` to `https://www.bitrise.io/app/1d190f1c0e4c8486#` in this particular case) but the page is not getting loaded.
The second URL gets loaded correctly after page reload.
Browser: Chrome 58.0.3029.110 on macOS

And here is that place with app name:
![zrzut ekranu 2017-05-17 o 12 28 40](https://cloud.githubusercontent.com/assets/3340954/26149895/69abeea4-3afc-11e7-8c48-518ad5dba822.png)

**Comment by erosdome** [comment] 2017-05-17 11:20
Thanks for reporting, soon to be resolved. Closing due to being duplicate of [#105](https://github.com/bitrise-io/bitrise-workflow-editor/issues/105)

**Closed by erosdome** 2017-05-17 11:20 UTC
